spring:
  application:
    name: admachine
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maxLifetime: 1765000
      maximumPoolSize: 50
      minimumIdle: 1
      connectionTimeout: 30000
      idleTimeout: 600000
      pool-name: database-admachine-pool
      connection-init-sql: select 1 from dual
mybatis:
  configuration:
    multiple-result-sets-enabled: true
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    jdbc-type-for-null: null
  mapper-locations: mappers/**/*.xml
---
spring:
  profiles: default

xiaomi:
  customer-service:
    apiHost: test.xiaomi.com
    secret: gg
message: chenfei xien0（543293557@qq.com）
